# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-07 03:08
from __future__ import unicode_literals

import common.thumbs
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='\u6635\u79f0\u957f\u5ea64-20\u4e2a\u5b57\u7b26\uff0c\u652f\u6301\u4e2d\u82f1\u6587\u3001\u6570\u5b57\u3001-\u3001_', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_\u4e00-\u9fa5]+$', '\u6635\u79f0\u957f\u5ea64-20\u4e2a\u5b57\u7b26\uff0c\u652f\u6301\u4e2d\u82f1\u6587\u3001\u6570\u5b57\u3001-\u3001_', 'invalid')], verbose_name='\u6635\u79f0')),
                ('chi_spell', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6635\u79f0\u4e2d\u6587\u62fc\u97f3\u7b80\u79f0')),
                ('chi_spell_all', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6635\u79f0\u4e2d\u6587\u62fc\u97f3\u5168\u62fc')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='\u6635\u79f0\u9996\u5b57')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='\u6635\u79f0\u5c3e\u5b57')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='\u90ae\u7bb1')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5bc6\u7801')),
                ('is_password_set', models.BooleanField(default=True, help_text='true\uff1a\u8bbe\u7f6e\u5bc6\u7801\uff0cfalse\uff1a\u968f\u673a\u5bc6\u7801(\u624b\u673a\u9a8c\u8bc1\u7801\u6ce8\u518c\u65f6\u968f\u673a\u751f\u6210)', verbose_name='\u662f\u5426\u8bbe\u7f6e\u5bc6\u7801')),
                ('is_username_set', models.BooleanField(default=True, help_text='true\uff1a\u8bbe\u7f6e\u6635\u79f0\uff0cfalse\uff1a\u968f\u673a\u6635\u79f0(\u624b\u673a\u9a8c\u8bc1\u7801\u6ce8\u518c\u65f6\u968f\u673a\u751f\u6210)', verbose_name='\u662f\u5426\u8bbe\u7f6e\u6635\u79f0')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('avatar', common.thumbs.ImageWithThumbsField(blank=True, max_length=800, null=True, upload_to='avatar/%Y/%m/%d/%H/%M%S')),
                ('mobile', models.CharField(default=None, max_length=100, null=True, unique=True, verbose_name='\u624b\u673a\u53f7')),
                ('province', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='\u7701\u4efd')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='\u57ce\u5e02')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5730\u533a')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8be6\u7ec6\u5730\u5740')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, '\u4fdd\u5bc6'), (1, '\u7537'), (2, '\u5973')], default=0, null=True, verbose_name='\u6027\u522b')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u7b80\u4ecb')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('career', models.CharField(blank=True, choices=[('5', '\u623f\u5730\u4ea7'), ('10', '\u56fd\u6709\u4f01\u4e1a'), ('2', '\u6559\u79d1\u6587'), ('3', '\u91d1\u878d'), ('4', '\u5546\u8d38'), ('9', '\u4e8b\u4e1a\u5355\u4f4d'), ('1', '\u653f\u5e9c\u90e8\u95e8'), ('6', '\u5236\u9020\u4e1a'), ('7', '\u81ea\u7531\u804c\u4e1a'), ('8', '\u5176\u4ed6')], max_length=20, null=True, verbose_name='\u804c\u4e1a')),
                ('qq', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('we_chat', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='\u5fae\u4fe1')),
                ('we_bo', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='\u5fae\u535a')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('verified_status', models.SmallIntegerField(choices=[(-1, '\u672a\u63d0\u4ea4'), (0, '\u5ba1\u6838\u4e2d'), (1, '\u5df2\u8ba4\u8bc1'), (2, '\u5ba1\u6838\u5931\u8d25')], default=-1, verbose_name='\u8ba4\u8bc1\u72b6\u6001')),
                ('verified_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8ba4\u8bc1\u8bf4\u660e')),
                ('is_system', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7cfb\u7edf\u7528\u6237')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'permissions': (('view_user', '\u7528\u6237\u7684\u53ea\u8bfb\u6743\u9650'),),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MobileCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='\u624b\u673a\u7684\u56fd\u5bb6\\\u5730\u533a\u533a\u53f7', max_length=10, verbose_name='\u624b\u673a\u7684\u56fd\u5bb6\\\u5730\u533a\u533a\u53f7')),
                ('zone', models.CharField(help_text='\u56fd\u5bb6\\\u5730\u533a', max_length=30, verbose_name='\u56fd\u5bb6\\\u5730\u533a')),
                ('min_digit', models.PositiveIntegerField(default=0)),
                ('max_digit', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '\u624b\u673a\u7684\u56fd\u5bb6\\\u5730\u533a\u533a\u53f7',
                'verbose_name_plural': '\u624b\u673a\u7684\u56fd\u5bb6\\\u5730\u533a\u533a\u53f7',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_user', to='accounts.MobileCode', verbose_name='\u624b\u673a\u533a\u53f7'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
