# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-07 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='\u662f\u5426\u662f\u804c\u5458'),
        ),
    ]
