# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.SmallIntegerField(blank=True, choices=[(0, '\u65e0'), (1, '\u65c5\u6e38\u653b\u7565'), (2, '\u5a31\u4e50\u8d44\u8baf'), (3, '\u6e38\u620f\u653b\u7565'), (4, '\u8d2d\u7269\u6298\u6263'), (5, '\u91d1\u878d\u5f00\u6237'), (6, '\u7f8e\u98df\u653b\u7565'), (7, '\u5176\u4ed6')], default=0, null=True, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('auth', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4f5c\u8005')),
                ('text', models.TextField(help_text='\u6b63\u6587', verbose_name='\u6b63\u6587')),
                ('crawl_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u722c\u53d6\u65f6\u95f4')),
                ('is_release', models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d1\u5e03')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u722c\u53d6\u65f6\u95f4')),
                ('retweets_count', models.PositiveIntegerField(default=0, editable=False, help_text='\u8f6c\u53d1\u6570', verbose_name='\u8f6c\u53d1\u6570')),
                ('comments_count', models.PositiveIntegerField(default=0, editable=False, help_text='\u56de\u590d\u6570', verbose_name='\u56de\u590d\u6570')),
                ('attitudes_count', models.PositiveIntegerField(default=0, editable=False, help_text='\u8d5e\u6570', verbose_name='\u8d5e\u6570')),
                ('favorites_count', models.PositiveIntegerField(default=0, editable=False, help_text='\u6536\u85cf\u6570', verbose_name='\u6536\u85cf\u6570')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, help_text='\u9605\u8bfb\u6570', verbose_name='\u9605\u8bfb\u6570')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u7ba1\u7406',
                'verbose_name_plural': '\u6587\u7ae0\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_type', models.SmallIntegerField(blank=True, choices=[(-1, '\u65e0'), (0, '\u5fae\u4fe1\u516c\u4f17\u53f7'), (1, '\u767e\u5ea6\u767e\u5bb6\u53f7'), (2, '\u4eca\u65e5\u5934\u6761\u53f7'), (3, '\u65b0\u6d6a\u5fae\u535a\u5e73\u53f0'), (4, 'qq\u65b0\u95fb'), (5, '\u7f51\u6613\u53f7\u5e73\u53f0'), (6, '\u963f\u91ccUC\u5e73\u53f0'), (7, '\u6296\u97f3\u5e73\u53f0'), (8, '\u77e5\u4e4e')], default=-1, null=True, verbose_name='\u5e73\u53f0\u540d\u79f0')),
                ('platform_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5e73\u53f0\u8d26\u53f7')),
                ('platform_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5e73\u53f0\u5bc6\u7801')),
                ('platform_openid', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5e73\u53f0openid')),
                ('platform_appid', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5e73\u53f0appid')),
                ('fans_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5173\u6ce8\u6570')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u81ea\u5a92\u4f53\u5e73\u53f0',
                'verbose_name_plural': '\u81ea\u5a92\u4f53\u5e73\u53f0',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='we_media.Platform', verbose_name='\u81ea\u5a92\u4f53\u5e73\u53f0'),
        ),
    ]
