# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-10 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_media', '0003_platform_platform_nickneme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='platform_nickneme',
            new_name='platform_nickname',
        ),
    ]
