# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-14 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_media', '0005_content_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_crawl',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u722c\u53d6\u7684\u6587\u7ae0'),
        ),
    ]
