# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-14 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('we_media', '0006_content_is_crawl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
