# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-14 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_media', '0007_auto_20190114_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
    ]
